angular.module(
    'eu.crismaproject.pilotE.controllers',
    [
        'ngTable',
        'ui.bootstrap.alert',
        'ui.bootstrap.modal',
        'eu.crismaproject.pilotE.services',
        'google-maps',
        'de.cismet.commons.angular.angularTools'
    ]
);