angular.module(
    'eu.crismaproject.pilotE',
    [
        'eu.crismaproject.pilotE.controllers',
        'eu.crismaproject.pilotE.directives',
        'eu.crismaproject.pilotE.services',
        'ui.bootstrap'
    ]
);
